apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-cpu1
spec:
  selector:
    matchLabels:
      color: black
  replicas: 1
  template:
    metadata:
      labels:
        color: black
    spec:
      containers:
      - name: autoscaletest-nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: autoscaletest-np
spec:
  ports:
    - name: autoscaleest-port
      port: 8080
      targetPort: 80
      nodePort: 30001
  selector:
    color: black
  type: NodePort
